config/routes.rb
Giftkart::Application.routes.draw do

  resources :users
  resources :orders do
    get 'checkout', :on => :collection
  end

  root to: 'welcomes#home'

  match '/signup',  to: 'users#new'

  get "welcomes/home"

  get "welcomes/flowers"

  get "welcomes/chocolates"

  get "welcomes/contact"

  get "welcomes/signin"

  # The priority is based upon orders of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcomes#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user

  attr_accessible :item, :price, :sender, :recipient

  validates_presence_of :item, :price
  validates :sender, :presence => true, :length => { :maximum => 50 }
  validates :recipient, :presence => true, :length => { :maximum => 50 }
  validate :price_has_to_be_greater_than_minimum

  def price_has_to_be_greater_than_minimum
    errors.add(:price, "price has to be greater than 0.01") if !price.blank? and price <= 0.01
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base

  has_many :orders

  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  before_save { |user| user.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_senitive: false }

  validates :password, presence: true, length: { minimum: 6 }
  validates_presence_of :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def checkout
    @order = Order.new
    @order.item = params[:item]
    if params[:item] == "Flowers"
      @order.price = 15.00
    elsif params[:item] == "Chocolates"
      @order.price = 10.00
    end
    render 'checkout'
  end

  def create
    @order = Order.new(params[:order])
    respond_to do |format|
      if @order.save
        @message = "Congratulations! You just gifted #{@order.item} to #{@order.recipient}"
        format.js { render 'order.js' }
      else
        render 'checkout'
      end
    end
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all

    respond_to do |format|
      format.html {render 'index'}# index.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def create
    @item = params[:user].delete(:item)
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        flash[:success] = "Congrats! Your account is created"
        format.html { render 'orders/cart' }
        format.xml { render :xml => @user }
      else
        format.html { render 'new' }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def new
    @item = params[:item]
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    render 'edit'
  end


  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html { render 'show'}
      format.xml { render :xml => @user }
    end
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "GiftKart Website"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "GiftKart", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    'welcomes/home' %></li>
          <li><%= link_to "Sign In", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/orders/cart.html.erb
<% provide(:title, @user.name) %>
<h1> Hello <%= @user.name %></h1>
<h2> You picked <%= @item %> to gift </h2>
<%= link_to "Continue", checkout_orders_path + "?item=" + @item, class: "btn btn-large btn-primary" %>

app/views/orders/checkout.html.erb
<% provide(:title, 'Your Order') %>

<div id="your_order">

    <h1>Your Order</h1>

    <div class="row">
      <div class="span6 offset3">
        <div>
          Item: <%= @order.item %>
        </div>
        <br />
        <div>
          Price: <%= @order.price %> $
        </div>
        <br />
        <%= form_for @order, :remote => true do |f| %>
            <%=  f.hidden_field :item, :value => @order.item  %>

            <%= f.hidden_field :price, :value => @order.price %>

            <%= f.label :sender %>
            <%= f.text_field :sender %>

            <%= f.label :recipient %>
            <%= f.text_field :recipient %>

            <%= f.submit "Place Order", class: "btn btn-large btn-primary" %>
        <% end %>
      </div>
    </div>
</div>

<div>
  <h1 id="order_status"></h1>
</div>

app/views/orders/order.js.erb
$('#your_order').remove();
$('#order_status').append( " <%= @message %>" );

app/views/orders/show.html.erb
<% provide(:title, @order.item) %>
<h1>  Congratulations! You just gifted  <%=@order.item%> to <%= @order.recipient %></h1>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Users</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Update my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @user.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b> User </b>
</p>

<p>
  <b>Name</b>
  <%= @user.name %>
</p>

<p>
  <b>Email</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', user_path %>

app/views/welcomes/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to GiftKart!</h1>

  <h2>
    Choose from a world of Flowers and Chocolates as gift!
  </h2>
  <%=  %>
  <%= link_to (image_tag "Flowers.jpg"), signup_path + "?item=Flowers" %>
  <%= link_to (image_tag "Chocolates.jpg"), signup_path + "?item=Chocolates" %>
</div>